emilpanelpro = {
    "MainMenu": [
        {"name": "Panels", "pic": "panels.png", "handler": "Panels"},
        {"name": "Plugins", "pic": "plugins.png", "handler": "Plugins"},
        {"name": "Tools", "pic": "tools.png", "handler": "Tools"},
        {"name": "SystemPlugins", "pic": "system.png", "handler": "SystemPlugins"},
        {"name": "Channels", "pic": "channels.png", "handler": "Channels"},
        {"name": "Media", "pic": "media.png", "handler": "Media"},
        {"name": "MultibootPlugins", "pic": "multiboot.png", "handler": "MultibootPlugins"},
        {"name": "Softcams", "pic": "emu.png", "handler": "Softcams"},
        {"name": "BackupSettings", "pic": "backup.png", "handler": "BackupSettings"},
        {"name": "RestoreSettings", "pic": "backup.png", "handler": "RestoreSettings"},
        {"name": "Images", "pic": "images.png", "handler": "Images"},
        {"name": "Picons", "pic": "picon.png", "handler": "Picons"},
        {"name": "Bootlogos", "pic": "bootlogo.png", "handler": "Bootlogos"},
        {"name": "Skins", "pic": "skins.png", "handler": "Skins"}
    ],
    
    "Channels": {
        "Other": {
            "icon": "channels.png",
            "items": [
                {"name": "Emil Nabil", "url": "https://raw.githubusercontent.com/emilnabil/channel-emil-nabil/main/installer.sh"},
                {"name": "Khaled Ali", "url": "https://raw.githubusercontent.com/emilnabil/channel-khaled/main/installer.sh"},
                {"name": "Mohamed Goda", "url": "https://raw.githubusercontent.com/emilnabil/channel-mohamed-goda/main/installer.sh"},
                {"name": "Tarek Ashry", "url": "https://raw.githubusercontent.com/emilnabil/channel-tarek-ashry/main/installer.sh"},
                {"name": "Elsafty-Tv-Radio-Steaming", "url": "https://dreambox4u.com/emilnabil237/settings/elsafty/installer.sh"}
            ]
        },
        "Ciefp": {
            "icon": "ciefp.png",
            "items": [
                {"name": "ciefp-channels-e2-75e-34w", "url": "https://raw.githubusercontent.com/emilnabil/download-plugins/main/ciefp-channels-e2/ciefp-channels-e2-75e-34w.sh"},
                {"name": "1sat-19E", "url": "https://raw.githubusercontent.com/emilnabil/download-plugins/refs/heads/main/ciefp-channels-e2/ciefp-E2-1sat-19E.sh"},
                {"name": "2satA-19E-13E", "url": "https://raw.githubusercontent.com/emilnabil/download-plugins/refs/heads/main/ciefp-channels-e2/ciefp-E2-2satA-19E-13E.sh"},
                {"name": "2satB-19E-16E", "url": "https://raw.githubusercontent.com/emilnabil/download-plugins/refs/heads/main/ciefp-channels-e2/ciefp-E2-2satB-19E-16E.sh"},
                {"name": "3satA-9E-10E-13E", "url": "https://raw.githubusercontent.com/emilnabil/download-plugins/refs/heads/main/ciefp-channels-e2/ciefp-E2-3satA-9E-10E-13E.sh"},
                {"name": "3satB-19E-16E-13E", "url": "https://raw.githubusercontent.com/emilnabil/download-plugins/refs/heads/main/ciefp-channels-e2/ciefp-E2-3satB-19E-16E-13E.sh"},
                {"name": "4satA-28E-19E-13E-30W", "url": "https://raw.githubusercontent.com/emilnabil/download-plugins/refs/heads/main/ciefp-channels-e2/ciefp-E2-4satA-28E-19E-13E-30W.sh"},
                {"name": "4satB-19E-16E-13E-0.8W", "url": "https://raw.githubusercontent.com/emilnabil/download-plugins/refs/heads/main/ciefp-channels-e2/ciefp-E2-4satB-19E-16E-13E-0.8W.sh"},
                {"name": "5sat-19E-16E-13E-1.9E-0.8W", "url": "https://raw.githubusercontent.com/emilnabil/download-plugins/refs/heads/main/ciefp-channels-e2/ciefp-E2-5sat-19E-16E-13E-1.9E-0.8W.sh"},
                {"name": "6sat-23E-19E-16E-13E-1.9E-0.8W", "url": "https://raw.githubusercontent.com/emilnabil/download-plugins/refs/heads/main/ciefp-channels-e2/ciefp-E2-6sat-23E-19E-16E-13E-1.9E-0.8W.sh"},
                {"name": "7sat-23E-19E-16E-13E-4.8E-1.9E-0.8W", "url": "https://raw.githubusercontent.com/emilnabil/download-plugins/refs/heads/main/ciefp-channels-e2/ciefp-E2-7sat-23E-19E-16E-13E-4.8E-1.9E-0.8W.sh"},
                {"name": "8sat-28E-23E-19E-16E-13E-4.8E-1.9E-0.8W", "url": "https://raw.githubusercontent.com/emilnabil/download-plugins/refs/heads/main/ciefp-channels-e2/ciefp-E2-8sat-28E-23E-19E-16E-13E-4.8E-1.9E-0.8W.sh"},
                {"name": "9sat-28E-23E-19E-16E-13E-9E-1.9E-0.8W-5W", "url": "https://raw.githubusercontent.com/emilnabil/download-plugins/refs/heads/main/ciefp-channels-e2/ciefp-E2-9sat-28E-23E-19E-16E-13E-9E-1.9E-0.8W-5W.sh"},
                {"name": "10sat-39E-28E-23E-19E-16E-13E-9E-4.8E-1.9E-0.8W", "url": "https://raw.githubusercontent.com/emilnabil/download-plugins/refs/heads/main/ciefp-channels-e2/ciefp-E2-10sat.sh"},
                {"name": "13sat-42E-39E-28E-23E-19E-16E-13E-9E-7E-4.8E-1.9E-0.8w-5w", "url": "https://raw.githubusercontent.com/emilnabil/download-plugins/refs/heads/main/ciefp-channels-e2/ciefp-E2-13sat.sh"},
                {"name": "16sat-42E-39E-28E-26E-23E-19E-16E-13E-10E-9E-7E-4.8E-1.9E-0.8w-4W-5w", "url": "https://raw.githubusercontent.com/emilnabil/download-plugins/refs/heads/main/ciefp-channels-e2/ciefp-E2-16sat.sh"},
                {"name": "18sat-42E-39E-36E-33E-28E-26E-23E-19E-16E-13E-10E-9E-7E-4.8E-1.9E-0.8w-4w-5w", "url": "https://raw.githubusercontent.com/emilnabil/download-plugins/refs/heads/main/ciefp-channels-e2/ciefp-E2-18sat.sh"}
            ]
        },
        "morph883": {
            "icon": "morpheus883.png",
            "items": [
                {"name": "Morph883_0.8W-4.8E-13E", "url": "https://raw.githubusercontent.com/emilnabil/download-plugins/refs/heads/main/morpheus883-channels/E2_Morph883_0.8W-4.8E-13E.sh"},
                {"name": "Morph883_0.8W-13E-19.2E-28.2E", "url": "https://raw.githubusercontent.com/emilnabil/download-plugins/refs/heads/main/morpheus883-channels/E2_Morph883_0.8W-13E-19.2E-28.2E.sh"},
                {"name": "Morph883_0.8W-13E-19.2E", "url": "https://raw.githubusercontent.com/emilnabil/download-plugins/refs/heads/main/morpheus883-channels/E2_Morph883_0.8W-13E-19.2E.sh"},
                {"name": "Morph883_0.8W-13E", "url": "https://raw.githubusercontent.com/emilnabil/download-plugins/refs/heads/main/morpheus883-channels/E2_Morph883_0.8W-13E.sh"},
                {"name": "Morph883_4.8E-13E-19.2E", "url": "https://raw.githubusercontent.com/emilnabil/download-plugins/refs/heads/main/morpheus883-channels/E2_Morph883_4.8E-13E-19.2E.sh"},
                {"name": "Morph883_4.8E-13E", "url": "https://raw.githubusercontent.com/emilnabil/download-plugins/refs/heads/main/morpheus883-channels/E2_Morph883_4.8E-13E.sh"},
                {"name": "Morph883_9E-13E-19.2E", "url": "https://raw.githubusercontent.com/emilnabil/download-plugins/refs/heads/main/morpheus883-channels/E2_Morph883_9E-13E-19.2E.sh"},
                {"name": "Morph883_9E-13E", "url": "https://raw.githubusercontent.com/emilnabil/download-plugins/refs/heads/main/morpheus883-channels/E2_Morph883_9E-13E.sh"},
                {"name": "Morph883_13E-16E-19.2E", "url": "https://raw.githubusercontent.com/emilnabil/download-plugins/refs/heads/main/morpheus883-channels/E2_Morph883_13E-16E-19.2E.sh"},
                {"name": "Morph883_13E-16E", "url": "https://raw.githubusercontent.com/emilnabil/download-plugins/refs/heads/main/morpheus883-channels/E2_Morph883_13E-16E.sh"},
                {"name": "Morph883_13E-19.2E-23.5E-28.2E", "url": "https://raw.githubusercontent.com/emilnabil/download-plugins/refs/heads/main/morpheus883-channels/E2_Morph883_13E-19.2E-23.5E-28.2E.sh"},
                {"name": "Morph883_13E-19.2E-23.5E", "url": "https://raw.githubusercontent.com/emilnabil/download-plugins/refs/heads/main/morpheus883-channels/E2_Morph883_13E-19.2E-23.5E.sh"},
                {"name": "Morph883_13E-19.2E-28.2E", "url": "https://raw.githubusercontent.com/emilnabil/download-plugins/refs/heads/main/morpheus883-channels/E2_Morph883_13E-19.2E-28.2E.sh"},
                {"name": "Morph883_13E-19.2E-42E", "url": "https://raw.githubusercontent.com/emilnabil/download-plugins/refs/heads/main/morpheus883-channels/E2_Morph883_13E-19.2E-42E.sh"},
                {"name": "Morph883_13E-19.2E.sh", "url": "https://raw.githubusercontent.com/emilnabil/download-plugins/refs/heads/main/morpheus883-channels/E2_Morph883_13E-19.2E.sh"},
                {"name": "Morph883_13E-23.5E", "url": "https://raw.githubusercontent.com/emilnabil/download-plugins/refs/heads/main/morpheus883-channels/E2_Morph883_13E-23.5E.sh"},
                {"name": "Morph883_13E-28.2E", "url": "https://raw.githubusercontent.com/emilnabil/download-plugins/refs/heads/main/morpheus883-channels/E2_Morph883_13E-28.2E.sh"},
                {"name": "Morph883_13E-42E", "url": "https://raw.githubusercontent.com/emilnabil/download-plugins/refs/heads/main/morpheus883-channels/E2_Morph883_13E-42E.sh"},
                {"name": "Morph883_13E", "url": "https://raw.githubusercontent.com/emilnabil/download-plugins/refs/heads/main/morpheus883-channels/E2_Morph883_13E.sh"},
                {"name": "Morph883_30W-13E-19.2E", "url": "https://raw.githubusercontent.com/emilnabil/download-plugins/refs/heads/main/morpheus883-channels/E2_Morph883_30W-13E-19.2E.sh"},
                {"name": "Morph883_30W-13E", "url": "https://raw.githubusercontent.com/emilnabil/download-plugins/refs/heads/main/morpheus883-channels/E2_Morph883_30W-13E.sh"},
                {"name": "Morph883_Motor", "url": "https://raw.githubusercontent.com/emilnabil/download-plugins/refs/heads/main/morpheus883-channels/E2_Morph883_Motor.sh"},
                {"name": "Morph883_Settings", "url": "https://raw.githubusercontent.com/emilnabil/download-plugins/refs/heads/main/morpheus883-channels/E2_Morph883_Settings.sh"}
            ]
        },
        "vaninbal": {
            "icon": "vhannibal.png",
            "items": [
                {"name": "Vhaninibal-Dual-13-19E", "url": "https://raw.githubusercontent.com/emilnabil/download-plugins/refs/heads/main/vanenbal-channels/Vhannibal-Dual-13-19E.sh"},
                {"name": "Vhaninbal-Dual-DTT-Campania", "url": "https://raw.githubusercontent.com/emilnabil/download-plugins/refs/heads/main/vanenbal-channels/Vhannibal-Dual-DTT-Campania.sh"},
                {"name": "Vhaninbal-Dual-DTT-Italia", "url": "https://raw.githubusercontent.com/emilnabil/download-plugins/refs/heads/main/vanenbal-channels/Vhannibal-Dual-DTT-Italia.sh"},
                {"name": "Vhaninbal-Dual-DTT-Lazio", "url": "https://raw.githubusercontent.com/emilnabil/download-plugins/refs/heads/main/vanenbal-channels/Vhannibal-Dual-DTT-Lazio.sh"},
                {"name": "Vhaninbal-Dual-DTT-Lombardia", "url": "https://raw.githubusercontent.com/emilnabil/download-plugins/refs/heads/main/vanenbal-channels/Vhannibal-Dual-DTT-Lombardia.sh"},
                {"name": "Vhaninbal-Dual-DTT-Piemonte", "url": "https://raw.githubusercontent.com/emilnabil/download-plugins/refs/heads/main/vanenbal-channels/Vhannibal-Dual-DTT-Piemonte.sh"},
                {"name": "Vhaninbal-HotBird-13E", "url": "https://raw.githubusercontent.com/emilnabil/download-plugins/refs/heads/main/vanenbal-channels/Vhannibal-HotBird-13E.sh"},
                {"name": "Vhaninbal-HotBird-DTT-Campania", "url": "https://raw.githubusercontent.com/emilnabil/download-plugins/refs/heads/main/vanenbal-channels/Vhannibal-HotBird-DTT-Campania.sh"},
                {"name": "Vhaninbal-HotBird-DTT-Italia", "url": "https://raw.githubusercontent.com/emilnabil/download-plugins/refs/heads/main/vanenbal-channels/Vhannibal-HotBird-DTT-Italia.sh"},
                {"name": "Vhaninbal-HotBird-DTT-Lazio", "url": "https://raw.githubusercontent.com/emilnabil/download-plugins/refs/heads/main/vanenbal-channels/Vhannibal-HotBird-DTT-Lazio.sh"},
                {"name": "Vhaninbal-HotBird-DTT-Lombardia", "url": "https://raw.githubusercontent.com/emilnabil/download-plugins/refs/heads/main/vanenbal-channels/Vhannibal-HotBird-DTT-Lombardia.sh"},
                {"name": "Vhaninbal-HotBird-DTT-Piemonte", "url": "https://raw.githubusercontent.com/emilnabil/download-plugins/refs/heads/main/vanenbal-channels/Vhannibal-HotBird-DTT-Piemonte.sh"},
                {"name": "Vhaninbal-Motor-70E-45W", "url": "https://raw.githubusercontent.com/emilnabil/download-plugins/refs/heads/main/vanenbal-channels/Vhannibal-Motor-70E-45W.sh"},
                {"name": "Vhaninbal-Motor-DTT-Campania", "url": "https://raw.githubusercontent.com/emilnabil/download-plugins/refs/heads/main/vanenbal-channels/Vhannibal-Motor-DTT-Campania.sh"},
                {"name": "Vhaninbal-Motor-DTT-Italia", "url": "https://raw.githubusercontent.com/emilnabil/download-plugins/refs/heads/main/vanenbal-channels/Vhannibal-Motor-DTT-Italia.sh"},
                {"name": "Vhaninbal-Motor-DTT-Lazio", "url": "https://raw.githubusercontent.com/emilnabil/download-plugins/refs/heads/main/vanenbal-channels/Vhannibal-Motor-DTT-Lazio.sh"},
                {"name": "Vhaninbal-Motor-DTT-Lombardia", "url": "https://raw.githubusercontent.com/emilnabil/download-plugins/refs/heads/main/vanenbal-channels/Vhannibal-Motor-DTT-Lombardia.sh"},
                {"name": "Vhaninbal-Motor-DTT-Piemonte", "url": "https://raw.githubusercontent.com/emilnabil/download-plugins/refs/heads/main/vanenbal-channels/Vhannibal-Motor-DTT-Piemonte.sh"},
                {"name": "Vhaninbal-Motor-DTT-Romagna", "url": "https://raw.githubusercontent.com/emilnabil/download-plugins/refs/heads/main/vanenbal-channels/Vhannibal-Motor-DTT-Romagna.sh"},
                {"name": "Vhaninbal-Motor-DTT-Sardegna", "url": "https://raw.githubusercontent.com/emilnabil/download-plugins/refs/heads/main/vanenbal-channels/Vhannibal-Motor-DTT-Sardegna.sh"},
                {"name": "Vhaninbal-Motor-DTT-Sicilia", "url": "https://raw.githubusercontent.com/emilnabil/download-plugins/refs/heads/main/vanenbal-channels/Vhannibal-Motor-DTT-Sicilia.sh"},
                {"name": "Vhaninbal-Quadri-9-13-16-19-23E", "url": "https://raw.githubusercontent.com/emilnabil/download-plugins/refs/heads/main/vanenbal-channels/Vhannibal-Quadri-9-13-16-19-23E.sh"},
                {"name": "Vhaninbal-Quadri-13-19-5E-1W", "url": "https://raw.githubusercontent.com/emilnabil/download-plugins/refs/heads/main/vanenbal-channels/Vhannibal-Quadri-13-19-5E-1W.sh"},
                {"name": "Vhaninbal-Quadri-13-19-9E-5W", "url": "https://raw.githubusercontent.com/emilnabil/download-plugins/refs/heads/main/vanenbal-channels/Vhannibal-Quadri-13-19-9E-5W.sh"},
                {"name": "Vhaninbal-Quadri-13-19-23-28E", "url": "https://raw.githubusercontent.com/emilnabil/download-plugins/refs/heads/main/vanenbal-channels/Vhannibal-Quadri-13-19-23-28E.sh"},
                {"name": "Vhaninbal-Trial-13-19E-5W", "url": "https://raw.githubusercontent.com/emilnabil/download-plugins/refs/heads/main/vanenbal-channels/Vhannibal-Trial-13-19E-5W.sh"},
                {"name": "Vhaninbal-Trial-13-19E-30W", "url": "https://raw.githubusercontent.com/emilnabil/download-plugins/refs/heads/main/vanenbal-channels/Vhannibal-Trial-13-19E-30W.sh"}
            ]
        }
    },

    "SystemPlugins": [
        {"name": "3gmodemmanager", "pic": "3gmodem.png", "url": "https://dreambox4u.com/emilnabil237/plugins/3gmodemmanager/3gmodemmanager.sh"},
        {"name": "devicemanager", "pic": "devicemanger.png", "url": "https://raw.githubusercontent.com/emilnabil/download-plugins/refs/heads/main/devicemanager.sh"},
        {"name": "mountmanager", "pic": "mountmanger.png", "url": "https://dreambox4u.com/emilnabil237/plugins/mountmanager/installer.sh"},
        {"name": "setpasswd", "pic": "settpass.png", "url": "https://raw.githubusercontent.com/emilnabil/download-plugins/refs/heads/main/setpasswd.sh"},
        {"name": "Signalfinder", "pic": "signal.png", "url": "https://raw.githubusercontent.com/emilnabil/download-plugins/refs/heads/main/signalfinder.sh"},
        {"name": "softwaremanager", "pic": "software.png", "url": "https://raw.githubusercontent.com/emilnabil/download-plugins/refs/heads/main/softwaremanager.sh"},
        {"name": "Ts-Sateditor", "pic": "ts-sat.png", "url": "https://dreambox4u.com/emilnabil237/plugins/ts-sateditor/ts-sateditor.sh"},
        {"name": "Xmlupdate", "pic": "xmlupdate.png", "url": "https://dreambox4u.com/emilnabil237/plugins/xmlupdate/xmlupdate.sh"}
    ],

    "Tools": [
        {"name": "Wget", "pic": "wget.png", "url": "https://github.com/emilnabil/download-plugins/raw/refs/heads/main/wget.sh"},
        {"name": "Curl", "pic": "curl.png", "url": "https://github.com/emilnabil/download-plugins/raw/refs/heads/main/curl.sh"},
        {"name": "Update Enigma2 All Python", "pic": "update.png", "url": "https://raw.githubusercontent.com/emil237/updates-enigma/main/update-all-python.sh"},
        {"name": "Opkg tools", "pic": "opkg.png", "url": "http://dreambox4u.com/emilnabil237/script/opkg.sh"},
        {"name": "Super Script", "pic": "superscript.png", "url": "https://dreambox4u.com/emilnabil237/script/Super_Script.sh"},
        {"name": "Delete-password", "pic": "dellpass.png", "url": "https://github.com/emilnabil/download-plugins/raw/refs/heads/main/delete-password.sh"},
        {"name": "Change-Password-To-root", "pic": "passwdroot.png", "url": "https://github.com/emilnabil/download-plugins/raw/refs/heads/main/change-password-to-root.sh"},
        {"name": "CAM-abertis-astra-sm", "pic": "astrasm.png", "url": "https://dreambox4u.com/emilnabil237/script/CAM-abertis-astra.sh"},
        {"name": "FORMAT_HDD_TO-Ext4", "pic": "format.png", "url": "https://raw.githubusercontent.com/emil237/scripts/refs/heads/main/format-hdd.sh"},
        {"name": "Repair-Inodes-From-Hdd", "pic": "repair.png", "url": "https://raw.githubusercontent.com/emil237/scripts/refs/heads/main/repair-hdd.sh"},
        {"name": "FIX-ipk-installation", "pic": "fix.png", "url": "https://dreambox4u.com/emilnabil237/script/fix-ipk-package-installation.sh"},
        {"name": "Set_Time_NTP-Google", "pic": "time.png", "url": "https://dreambox4u.com/emilnabil237/script/set_time.sh"},
        {"name": "Fix Softcam Atv", "pic": "fixsoftcam.png", "url": "http://updates.mynonpublic.com/oea/feed"},
        {"name": "Fix Softcam OpenPli", "pic": "fixsoftcam.png", "url": "https://raw.githubusercontent.com/emil237/download-plugins/main/softcam-support-pli.sh"},
        {"name": "Wget package Vti", "pic": "wgetvti.png", "url": "https://raw.githubusercontent.com/emil237/download-plugins/refs/heads/main/tool_vti-wget_1.16.3.sh"},
        {"name": "Feed OpenPicons", "pic": "feed.png", "url": "https://dreambox4u.com/emilnabil237/script/openpicons-feed.sh"},
        {"name": "Zip2ipk", "pic": "zip.png", "url": "http://dreambox4u.com/emilnabil237/script/zip2ipk.sh"}
    ],

    "MultibootPlugins": [
        {"name": "EgamiBoot_10.5", "pic": "multiboot.png", "url": "https://raw.githubusercontent.com/emil237/egamiboot/refs/heads/main/installer.sh"},
        {"name": "EgamiBoot_10.6", "pic": "multiboot.png", "url": "https://raw.githubusercontent.com/emil237/egamiboot/refs/heads/main/egamiboot-10.6.sh"},
        {"name": "Neoboot_9.65", "pic": "multiboot.png", "url": "https://dreambox4u.com/emilnabil237/plugins/neoboot-v9.65/iNB.sh"},
        {"name": "Neoboot_9.65_mod-ElSafty", "pic": "multiboot.png", "url": "https://raw.githubusercontent.com/emil237/neoboot_v9.65/main/iNB_9.65_mod-elsafty.sh"},
        {"name": "Neoboot_9.60", "pic": "multiboot.png", "url": "https://dreambox4u.com/emilnabil237/plugins/neoboot-v9.60/iNB.sh"},
        {"name": "Neoboot_9.58", "pic": "multiboot.png", "url": "https://dreambox4u.com/emilnabil237/plugins/neoboot-v9.58/iNB.sh"},
        {"name": "Neoboot_9.54", "pic": "multiboot.png", "url": "https://raw.githubusercontent.com/emil237/neoboot_9.54/main/installer.sh"},
        {"name": "OpenMultiboot_1.3", "pic": "multiboot.png", "url": "https://raw.githubusercontent.com/emil237/openmultiboot/main/installer.sh"},
        {"name": "OpenMultiboot-E2turk", "pic": "multiboot.png", "url": "https://raw.githubusercontent.com/e2TURK/omb-enhanced/main/install.sh"},
        {"name": "Multiboot-FlashOnline", "pic": "multiboot.png", "url": "https://raw.githubusercontent.com/emil237/download-plugins/main/multiboot-flashonline.sh"}
    ],

    "Media": [
        {"name": "BouquetMakerXtream", "pic": "bouquetmaker.png", "url": "http://dreambox4u.com/emilnabil237/plugins/BouquetMakerXtream/installer.sh"},
        {"name": "E2m3u2Bouquet", "pic": "e2m3u2bouquet.png", "url": "https://dreambox4u.com/emilnabil237/plugins/e2m3u2bouquet/installer.sh"},
        {"name": "E2Player-MAXBAMBY", "pic": "e2iplayer.png", "url": "https://gitlab.com/maxbambi/e2iplayer/-/raw/master/install-e2iplayer.sh"},
        {"name": "E2Player-ZADMARIO", "pic": "e2iplayer.png", "url": "https://gitlab.com/zadmario/e2iplayer/-/raw/master/install-e2iplayer.sh"},
        {"name": "IptoSat", "pic": "iptosat.png", "url": "https://dreambox4u.com/emilnabil237/plugins/iptosat/installer.sh"},
        {"name": "IpAudio_6.7_py2", "pic": "ipaudio.png", "url": "https://dreambox4u.com/emilnabil237/plugins/ipaudio/installer.sh"},
        {"name": "IpAudio_7.4_py3", "pic": "ipaudio.png", "url": "https://dreambox4u.com/emilnabil237/plugins/ipaudio/ipaudio-7.4-ffmpeg.sh"},
        {"name": "IpAudioPro", "pic": "ipaudiopro.png", "url": "https://dreambox4u.com/emilnabil237/plugins/ipaudiopro/installer.sh"},
        {"name": "JediEpgExtream", "pic": "jediepgxtream.png", "url": "https://dreambox4u.com/emilnabil237/plugins/jediepgextream/installer.sh"},
        {"name": "jedimakerxtream", "pic": "jedimaker.png", "url": "https://dreambox4u.com/emilnabil237/plugins/jedimakerxtream/installer.sh"},
        {"name": "multistalker", "pic": "multistalker.png", "url": "https://dreambox4u.com/emilnabil237/plugins/multistalker/installer.sh"},
        {"name": "MultiStalkerPro", "pic": "multistalkerpro.png", "url": "https://raw.githubusercontent.com/emilnabil/multi-stalkerpro/main/installer.sh"},
        {"name": "Quarter pounder", "pic": "quarterpounder.png", "url": "http://dreambox4u.com/emilnabil237/script/quarterpounder.sh"},
        {"name": "Suptv", "pic": "suptv.png", "url": "https://raw.githubusercontent.com/emil237/suptv/main/installer.sh"},
        {"name": "YouTube", "pic": "youtube.png", "url": "https://dreambox4u.com/emilnabil237/plugins/YouTube/installer.sh"},
        {"name": "xklass-iptv", "pic": "xklass.png", "url": "https://dreambox4u.com/emilnabil237/plugins/xklass/installer.sh"},
        {"name": "Xtreamty", "pic": "xstreamity.png", "url": "https://dreambox4u.com/emilnabil237/plugins/xtreamity/installer.sh"},
        {"name": "Xcpluginforever", "pic": "xcplugin.png", "url": "https://raw.githubusercontent.com/Belfagor2005/xc_plugin_forever/main/installer.sh"}
    ],

    "Softcams": [
        {"name": "Cccam", "pic": "link.png", "url": "https://dreambox4u.com/emilnabil237/emu/installer-cccam.sh"},
        {"name": "gosatplus-ncam", "pic": "link.png", "url": "https://dreambox4u.com/emilnabil237/emu/installer-gosatplus-ncam.sh"},
        {"name": "gosatplus-oscam", "pic": "link.png", "url": "https://dreambox4u.com/emilnabil237/emu/installer-gosatplus-oscam.sh"},
        {"name": "gosatplus_v3_arm", "pic": "link.png", "url": "http://e2.gosatplus.com/Plugin/V3/arm-openpli-installer_py3_v3.sh"},
        {"name": "gosatplus_v3_mips", "pic": "link.png", "url": "http://e2.gosatplus.com/Plugin/V3/mips-openpli-installer_py3_v3.sh"},
        {"name": "gosatplus_v3_Fix", "pic": "link.png", "url": "http://e2.gosatplus.com/Plugin/V3/GosatPlusPluginFixPy.sh"},
        {"name": "Hold-flag-ncam", "pic": "link.png", "url": "https://dreambox4u.com/emilnabil237/script/Hold-flag-ncam.sh"},
        {"name": "Hold-flag-Oscam", "pic": "link.png", "url": "https://dreambox4u.com/emilnabil237/script/Hold-flag-Oscam.sh"},
        {"name": "Ncam", "pic": "link.png", "url": "https://dreambox4u.com/emilnabil237/emu/installer-ncam.sh"},
        {"name": "Oscam", "pic": "link.png", "url": "https://dreambox4u.com/emilnabil237/emu/installer-oscam.sh"},
        {"name": "Oscam-11.726-by-lenuxsat", "pic": "link.png", "url": "https://dreambox4u.com/emilnabil237/emu/oscam-by-lenuxsat/installer.sh"},
        {"name": "oscamicam", "pic": "link.png", "url": "https://dreambox4u.com/emilnabil237/emu/installer-oscamicam.sh"},
        {"name": "powercam_v2-icam-arm", "pic": "link.png", "url": "https://dreambox4u.com/emilnabil237/emu/powercam/installer.sh"},
        {"name": "powercam-Ncam", "pic": "link.png", "url": "https://dreambox4u.com/emilnabil237/emu/installer-powercam-ncam.sh"},
        {"name": "powercam-Oscam", "pic": "link.png", "url": "https://dreambox4u.com/emilnabil237/emu/installer-powercam-oscam.sh"},
        {"name": "Restore-flag-ncam", "pic": "link.png", "url": "https://dreambox4u.com/emilnabil237/script/Restore-flag-ncam.sh"},
        {"name": "Restore-flag-oscam", "pic": "link.png", "url": "https://dreambox4u.com/emilnabil237/script/Restore-flag-Oscam.sh"},
        {"name": "Revcam-Ncam", "pic": "link.png", "url": "https://dreambox4u.com/emilnabil237/emu/installer-revcam-ncam.sh"},
        {"name": "Revcam-Oscam", "pic": "link.png", "url": "https://dreambox4u.com/emilnabil237/emu/installer-revcam-oscam.sh"},
        {"name": "Revcam", "pic": "link.png", "url": "https://dreambox4u.com/emilnabil237/emu/installer-revcam.sh"},
        {"name": "Supcam-Ncam", "pic": "link.png", "url": "https://dreambox4u.com/emilnabil237/emu/installer-supcam-ncam.sh"},
        {"name": "Supcam-Oscam", "pic": "link.png", "url": "https://dreambox4u.com/emilnabil237/emu/installer-supcam-oscam.sh"},
        {"name": "Ultracam-Ncam", "pic": "link.png", "url": "https://dreambox4u.com/emilnabil237/emu/installer-ultracam-ncam.sh"},
        {"name": "Ultracam-Oscam", "pic": "link.png", "url": "https://dreambox4u.com/emilnabil237/emu/installer-ultracam-oscam.sh"},
        {"name": "Ultracam", "pic": "link.png", "url": "https://dreambox4u.com/emilnabil237/emu/installer-ultracam.sh"}
    ],

    "Skins": {
        "OpenATV": {
            "icon": "openatv_icon.png",
            "items": [
                {"name": "Aglare-FHD", "url": "https://raw.githubusercontent.com/popking159/skins/refs/heads/main/aglareatv/installer.sh"},
                {"name": "Areadeltasat_fhd", "url": "https://github.com/emil237/skins-enigma2/raw/refs/heads/main/ATV/skins_areadeltasat_fhd_dragon_1_9_Poster_Backdrop.sh"},
                {"name": "Fury-FHD", "url": "https://raw.githubusercontent.com/islam-2412/IPKS/refs/heads/main/fury/installer.sh"},
                {"name": "Maxy-FHD", "url": "https://raw.githubusercontent.com/popking159/skins/refs/heads/main/maxyatv/installer.sh"},
                {"name": "Full HD Glass17", "url": "http://dreambox4u.com/emilnabil237/skins/skin-fullhdglass17/installer.sh"},
                {"name": "MyMetrixLiteBackup", "url": "https://raw.githubusercontent.com/emilnabil/download-plugins/refs/heads/main/skin-MyMetrixLiteBackup.sh"},
                {"name": "MetrixFHD-Extraevent-PosterXD", "url": "https://dreambox4u.com/emilnabil237/skins/openatv/SKIN-MetrixFHD-OpenATV-Extraevent-PosterX.sh"},
                {"name": "malek-fhd", "url": "https://raw.githubusercontent.com/emil237/skins-enigma2/main/ATV/skins-malek-fhd_2.2_py3.11.2-py3.12.1.sh"},
                {"name": "Nacht_1.7.3", "url": "http://dreambox4u.com/emilnabil237/script/SKIN-ATV-nacht_1.7.3.sh"},
                {"name": "Ozeta-Xtra", "url": "http://dreambox4u.com/emilnabil237/script/SKIN-ATV-ozeta-xtra.sh"},
                {"name": "XDreamy-FHD", "url": "https://raw.githubusercontent.com/Insprion80/Skins/main/xDreamy/installer.sh"}
            ]
        },
        "TeamNitro": {
            "icon": "teamnitro.png",
            "items": [
                {"name": "TeamNitro Control", "url": "https://gitlab.com/emilnabil1/teamnitro/-/raw/main/SKIN-teamnitro.sh"},
                {"name": "AlAyam-FHD", "url": "https://raw.githubusercontent.com/biko-73/TeamNitro/main/script/installerAL.sh"},
                {"name": "Desert-FHD", "url": "https://gitlab.com/emilnabil1/teamnitro/-/raw/main/installer-skin-desert.sh"},
                {"name": "BoHLALA-FHD", "url": "https://gitlab.com/emilnabil1/teamnitro/-/raw/main/installer.sh"},
                {"name": "Dragon-FHD", "url": "https://raw.githubusercontent.com/biko-73/TeamNitro/main/script/installerD.sh"},
                {"name": "NitroAdvance-FHD", "url": "https://raw.githubusercontent.com/biko-73/TeamNitro/main/script/installerN.sh"},
                {"name": "Klll-Pro-FHD", "url": "https://raw.githubusercontent.com/biko-73/zelda77/main/installer.sh"}
            ]
        },
        "OpenBH": {
            "icon": "openbh_icon.png",
            "items": [
                {"name": "Aglare-fhd", "url": "https://raw.githubusercontent.com/popking159/skins/refs/heads/main/aglarepli/installer.sh"},
                {"name": "Fury-FHD", "url": "https://raw.githubusercontent.com/islam-2412/IPKS/refs/heads/main/fury/installer.sh"},
                {"name": "MX_BlackSea", "url": "https://dreambox4u.com/emilnabil237/skins/obh/skins-MX_BlackSea.sh"},
                {"name": "MX-Sline-Black-Red-Gradient", "url": "https://dreambox4u.com/emilnabil237/skins/obh/mx-sline-black-red-gradient_py3.12.sh"},
                {"name": "MX_Sline-Blue", "url": "https://dreambox4u.com/emilnabil237/skins/obh/MX_Sline-Blue_OBH_5.4_py3.12_py3.12.sh"},
                {"name": "MX_Sline-Red_X2", "url": "https://dreambox4u.com/emilnabil237/skins/obh/MX_Sline-Red_X2_py3.12.sh"},
                {"name": "OpenBhGreenFHD", "url": "https://dreambox4u.com/emilnabil237/skins/obh/skin_OpenBhGreenFHD.sh"},
                {"name": "XDreamy-FHD", "url": "https://raw.githubusercontent.com/Insprion80/Skins/main/xDreamy/installer.sh"},
                {"name": "Youchie-OBH-FHD", "url": "https://raw.githubusercontent.com/emilnabil/skins-obh/refs/heads/main/skin-Youchie-OBH-FHD.sh"}
            ]
        },
        "Egami": {
            "icon": "egami_icon.png",
            "items": [
                {"name": "Aglare-FHD", "url": "https://raw.githubusercontent.com/popking159/skins/refs/heads/main/aglareatv/installer.sh"},
                {"name": "Fury-FHD", "url": "https://raw.githubusercontent.com/islam-2412/IPKS/refs/heads/main/fury/installer.sh"},
                {"name": "Premium-Fhd", "url": "https://dreambox4u.com/emilnabil237/skins/script/SKIN-egami-premium-fhd-py3.sh"},
                {"name": "Premium-Black-Fhd", "url": "https://dreambox4u.com/emilnabil237/skins/script/SKIN-egami-premium--black-fhd-py3.sh"},
                {"name": "Premium-Blue-Fhd", "url": "https://dreambox4u.com/emilnabil237/skins/script/SKIN-egami-premium--blue-fhd-py3.sh"},
                {"name": "XDreamy-FHD", "url": "https://raw.githubusercontent.com/Insprion80/Skins/main/xDreamy/installer.sh"}
            ]
        },
        "OpenPli_py3": {
            "icon": "openpli.png",
            "items": [
                {"name": "Aglare-FHD", "url": "https://raw.githubusercontent.com/popking159/skins/refs/heads/main/aglareatv/installer.sh"},
                {"name": "BARDO-FHD", "url": "https://raw.githubusercontent.com/emil237/skins-enigma2/refs/heads/main/pli/Skin-bardo-fhd_3.7.2.sh"},
                {"name": "BLACKNEON-XP_Mod_M-Nasr", "url": "https://dreambox4u.com/emilnabil237/skins/pli9x/Skin-BLACKNEON-XP_mod_mnasr-pli9x.sh"},
                {"name": "malek-fhd", "url": "https://raw.githubusercontent.com/emil237/skins-enigma2/main/pli/Skin-malek-fhd_1.2.sh"},
                {"name": "Ozeta-Xtra", "url": "http://dreambox4u.com/emilnabil237/script/SKIN-PLI-ozeta-xtra.sh"},
                {"name": "XDreamy-FHD", "url": "https://raw.githubusercontent.com/Insprion80/Skins/main/xDreamy/installer.sh"},
                {"name": "Youchie-PLI-FHD", "url": "https://raw.githubusercontent.com/emilnabil/skins-openpli-9x/refs/heads/main/skin-Youchie-PLI-FHD.sh"}
            ]
        },
        "OpenSpa": {
            "icon": "openspa.png",
            "items": [
                {"name": "Aglare-FHD", "url": "https://raw.githubusercontent.com/popking159/skins/refs/heads/main/aglareatv/installer.sh"},
                {"name": "Fury-FHD", "url": "https://raw.githubusercontent.com/islam-2412/IPKS/refs/heads/main/fury/installer.sh"},
                {"name": "estuary-1080-FHD", "url": "https://gitlab.com/elbrins/skins/-/raw/main/Spa/Skin-estuary-1080.sh"}
            ]
        },
        "OpenVix": {
            "icon": "openvix.png",
            "items": [
                {"name": "Aglare-FHD", "url": "https://raw.githubusercontent.com/popking159/skins/refs/heads/main/aglarepli/installer.sh"},
                {"name": "Fury-FHD", "url": "https://raw.githubusercontent.com/islam-2412/IPKS/refs/heads/main/fury/installer.sh"},
                {"name": "XDreamy-FHD", "url": "https://raw.githubusercontent.com/Insprion80/Skins/main/xDreamy/installer.sh"}
            ]
        },
        "OpenPli_py2": {
            "icon": "openpli.png",
            "items": [
                {"name": "Bluemetal-FHD", "url": "https://raw.githubusercontent.com/emil237/skins-enigma2/refs/heads/main/pli/Skin-bluemetal-fhd.sh"},
                {"name": "CH.LEAGUE-FHD", "url": "http://dreambox4u.com/emilnabil237/script/SKIN-PLI-CH.LEAGUE-FHD.sh"},
                {"name": "Maxy-FHD", "url": "https://dreambox4u.com/emilnabil237/skins/script/skins-Maxy-FHD.sh"},
                {"name": "Ozeta-Xtra", "url": "http://dreambox4u.com/emilnabil237/script/SKIN-PLI-ozeta-xtra.sh"},
                {"name": "QATAR-2022-V3-FHD", "url": "http://dreambox4u.com/emilnabil237/script/SKIN-PLI-QATAR-2022-V3-FHD.sh"},
                {"name": "SPIDERMAN-FHD", "url": "http://dreambox4u.com/emilnabil237/script/SKIN-PLI-SPIDERMAN-FHD.sh"},
                {"name": "WAR-S-FHD", "url": "http://dreambox4u.com/emilnabil237/script/SKIN-PLI-WAR-S-FHD.sh"},
                {"name": "BLACKSKY-S-HD", "url": "https://raw.githubusercontent.com/emil237/skins-enigma2/main/pli/SKIN-BLACKSKY-S-HD-MOD-By-Muaath.sh"},
                {"name": "BATMAN-MP-HD", "url": "https://raw.githubusercontent.com/emil237/skins-enigma2/main/pli/SKIN-BATMAN-MP-HD-By-Muaath.sh"},
                {"name": "TOKYO2020-FHD", "url": "https://raw.githubusercontent.com/emil237/skins-enigma2/main/pli/SKIN-TOKYO2020-FHD-By-Muaath.sh"}
            ]
        }
    },

    "Picons": [
        {"name": "intelsat_31.5w", "pic": "link.png", "url": "https://dreambox4u.com/emilnabil237/picons/intelsat_31.5w/installer.sh"},
        {"name": "hispasat_30.0w", "pic": "link.png", "url": "https://dreambox4u.com/emilnabil237/picons/hispasat_30.0w/installer.sh"},
        {"name": "intelsat_27.5w", "pic": "link.png", "url": "https://dreambox4u.com/emilnabil237/picons/intelsat_27.5w/installer.sh"},
        {"name": "intelsat_24.5w", "pic": "link.png", "url": "https://dreambox4u.com/emilnabil237/picons/intelsat_24.5w/installer.sh"},
        {"name": "ses4_22.0w", "pic": "link.png", "url": "https://dreambox4u.com/emilnabil237/picons/ses4_22.0w/installer.sh"},
        {"name": "nss7_20.0w", "pic": "link.png", "url": "https://dreambox4u.com/emilnabil237/picons/nss7_20.0w/installer.sh"},
        {"name": "telstar_15.0w", "pic": "link.png", "url": "https://dreambox4u.com/emilnabil237/picons/telstar_15.0w/installer.sh"},
        {"name": "express_14w", "pic": "link.png", "url": "https://dreambox4u.com/emilnabil237/picons/express_14w/installer.sh"},
        {"name": "express_11.0w-14.0w", "pic": "link.png", "url": "https://dreambox4u.com/emilnabil237/picons/express_11.0w-14.0w/installer.sh"},
        {"name": "Nilesat_7W-8W", "pic": "link.png", "url": "https://dreambox4u.com/emilnabil237/picons/nilesat/installer.sh"},
        {"name": "eutelsat_5.0w", "pic": "link.png", "url": "https://dreambox4u.com/emilnabil237/picons/eutelsat_5.0w/installer.sh"},
        {"name": "Amos_4.0W", "pic": "link.png", "url": "https://dreambox4u.com/emilnabil237/picons/amos_4.0w/installer.sh"},
        {"name": "abs_3.0w", "pic": "abs.png", "url": "https://dreambox4u.com/emilnabil237/picons/abs_3.0w/installer.sh"},
        {"name": "thor_0.8w", "pic": "link.png", "url": "https://dreambox4u.com/emilnabil237/picons/thor_0.8w/installer.sh"},
        {"name": "bulgariasat_1.9e", "pic": "link.png", "url": "https://dreambox4u.com/emilnabil237/picons/bulgariasat_1.9e/installer.sh"},
        {"name": "eutelsat_3.0e", "pic": "link.png", "url": "https://dreambox4u.com/emilnabil237/picons/eutelsat_3.0e/installer.sh"},
        {"name": "astra_4.8e", "pic": "link.png", "url": "https://dreambox4u.com/emilnabil237/picons/astra_4.8e/installer.sh"},
        {"name": "eutelsat_7.0e", "pic": "link.png", "url": "https://dreambox4u.com/emilnabil237/picons/eutelsat_7.0e/installer.sh"},
        {"name": "eutelsat_9.0e", "pic": "link.png", "url": "https://dreambox4u.com/emilnabil237/picons/eutelsat_9.0e/installer.sh"},
        {"name": "eutelsat_10.0e", "pic": "link.png", "url": "https://dreambox4u.com/emilnabil237/picons/eutelsat_10.0e/installer.sh"},
        {"name": "hotbird_13.0e", "pic": "link.png", "url": "https://dreambox4u.com/emilnabil237/picons/hotbird_13.0e/installer.sh"},
        {"name": "eutelsat_16.0e", "pic": "link.png", "url": "https://dreambox4u.com/emilnabil237/picons/eutelsat_16.0e/installer.sh"},
        {"name": "astra_19.2e", "pic": "link.png", "url": "https://dreambox4u.com/emilnabil237/picons/astra_19.2e/installer.sh"},
        {"name": "eutelsat_21.6e", "pic": "link.png", "url": "https://dreambox4u.com/emilnabil237/picons/eutelsat_21.6e/installer.sh"},
        {"name": "astra_23.5e", "pic": "link.png", "url": "https://dreambox4u.com/emilnabil237/picons/astra_23.5e/installer.sh"},
        {"name": "eshail_25.5e", "pic": "link.png", "url": "https://dreambox4u.com/emilnabil237/picons/eshail_25.5e/installer.sh"},
        {"name": "badr_26.0e", "pic": "link.png", "url": "https://dreambox4u.com/emilnabil237/picons/badr_26.0e/installer.sh"},
        {"name": "astra_28.2e", "pic": "link.png", "url": "https://dreambox4u.com/emilnabil237/picons/astra_28.2e/installer.sh"},
        {"name": "arabsat_30.5e", "pic": "link.png", "url": "https://dreambox4u.com/emilnabil237/picons/arabsat_30.5e/installer.sh"},
        {"name": "astra_31.5e", "pic": "link.png", "url": "https://dreambox4u.com/emilnabil237/picons/astra_31.5e/installer.sh"},
        {"name": "intelsat_33.0e", "pic": "link.png", "url": "https://dreambox4u.com/emilnabil237/picons/eutelsat-intelsat_33.0e/installer.sh"},
        {"name": "eutelsat_36.0e", "pic": "link.png", "url": "https://dreambox4u.com/emilnabil237/picons/eutelsat_36.0e/installer.sh"},
        {"name": "hellas-sat_39.0e", "pic": "link.png", "url": "https://dreambox4u.com/emilnabil237/picons/hellas-sat_39.0e/installer.sh"},
        {"name": "turksat_42.0e", "pic": "link.png", "url": "https://dreambox4u.com/emilnabil237/picons/turksat_42.0e/installer.sh"},
        {"name": "azerspace_45.0e", "pic": "link.png", "url": "https://dreambox4u.com/emilnabil237/picons/azerspace_45.0e/installer.sh"},
        {"name": "azerspace_46.0e", "pic": "link.png", "url": "https://dreambox4u.com/emilnabil237/picons/azerspace_46.0e/installer.sh"},
        {"name": "turksat_50.0e_56.0e_57e", "pic": "link.png", "url": "https://dreambox4u.com/emilnabil237/picons/turksat_50.0e_56.0e_57e/installer.sh"},
        {"name": "belintersat_51.5e", "pic": "link.png", "url": "https://dreambox4u.com/emilnabil237/picons/belintersat_51.5e/installer.sh"},
        {"name": "turkmenalem_52.0e", "pic": "link.png", "url": "https://dreambox4u.com/emilnabil237/picons/turkmenalem_52.0e/installer.sh"},
        {"name": "alyahsat_52.5e", "pic": "link.png", "url": "https://dreambox4u.com/emilnabil237/picons/alyahsat_52.5e/installer.sh"},
        {"name": "express_53.0e", "pic": "link.png", "url": "https://dreambox4u.com/emilnabil237/picons/express_53.0e/installer.sh"},
        {"name": "yamal_54.9e", "pic": "link.png", "url": "https://dreambox4u.com/emilnabil237/picons/gsat-yamal_54.9e/installer.sh"},
        {"name": "intelsat_60.0e_66.0e_68.0e", "pic": "link.png", "url": "https://dreambox4u.com/emilnabil237/picons/intelsat_60.0e_66.0e_68.0e/installer.sh"},
        {"name": "intelsat_62.0e", "pic": "link.png", "url": "https://dreambox4u.com/emilnabil237/picons/intelsat_62.0e/installer.sh"},
        {"name": "eutelsat_70.0e_74.9e_75.0e", "pic": "link.png", "url": "https://dreambox4u.com/emilnabil237/picons/eutelsat_70.0e_74.9e_75.0e/installer.sh"},
        {"name": "Intelsat_72.1e", "pic": "link.png", "url": "https://dreambox4u.com/emilnabil237/picons/Intelsat_72.1e/installer.sh"},
        {"name": "abs_75.0e", "pic": "link.png", "url": "https://dreambox4u.com/emilnabil237/picons/abs_75.0e/installer.sh"},
        {"name": "picons-other", "pic": "link.png", "url": "https://raw.githubusercontent.com/emil237/picon-other/main/installer.sh"},
        {"name": "Chocholousek-Picons", "pic": "link.png", "url": "https://github.com/s3n0/e2plugins/raw/master/ChocholousekPicons/online-setup"}
    ],

    "Bootlogos": [
        {"name": "BootlogoSwapper Atv", "pic": "link.png", "url": "http://dreambox4u.com/emilnabil237/script/bootlogoswapper-Atv.sh"},
        {"name": "Bootlogo-PURE2", "pic": "link.png", "url": "http://dreambox4u.com/emilnabil237/script/bootLogoswapper-Pure2.sh"},
        {"name": "BootlogoSwapper Christmas", "pic": "link.png", "url": "http://dreambox4u.com/emilnabil237/script/bootlogoswapper-christmas.sh"},
        {"name": "BootlogoSwapper Pli", "pic": "link.png", "url": "http://dreambox4u.com/emilnabil237/script/bootlogoswapper-pli.sh"},
        {"name": "BootlogoSwapper OpenBH", "pic": "link.png", "url": "http://dreambox4u.com/emilnabil237/script/bootlogoswapper-OpenBH.sh"},
        {"name": "BootlogoSwapper Egami", "pic": "link.png", "url": "http://dreambox4u.com/emilnabil237/script/bootLogoswapper-Egami.sh"},
        {"name": "BootlogoSwapper OpenVix", "pic": "link.png", "url": "http://dreambox4u.com/emilnabil237/script/bootlogoswapper-OpenVix.sh"},
        {"name": "BootlogoSwapper Kids", "pic": "link.png", "url": "http://dreambox4u.com/emilnabil237/script/bootlogoswapper-kids.sh"},
        {"name": "BootlogoSwapper Ramadan", "pic": "link.png", "url": "http://dreambox4u.com/emilnabil237/script/bootlogo-swapper-ramadan.sh"},
        {"name": "BootlogoSwapper Eid-Aldha", "pic": "link.png", "url": "http://dreambox4u.com/emilnabil237/script/bootlogoswaper-Eid-Aldha.sh"},
        {"name": "BootlogoSwapper V2.1", "pic": "link.png", "url": "http://dreambox4u.com/emilnabil237/script/BootlogoSwapper_v2.1.sh"},
        {"name": "BootlogoSwapper V2.3", "pic": "link.png", "url": "http://dreambox4u.com/emilnabil237/script/BootlogoSwapper_v2.3.sh"}
    ],

    "Panels": [
        {"name": "Ajpanel", "pic": "link.png", "url": "http://dreambox4u.com/emilnabil237/plugins/ajpanel/installer1.sh"},
        {"name": "AjPanel Custom Menu All Panels", "pic": "link.png", "url": "https://dreambox4u.com/emilnabil237/plugins/ajpanel/emil-panel-all.sh"},
        {"name": "Panel Lite By Emil Nabil", "pic": "link.png", "url": "https://dreambox4u.com/emilnabil237/plugins/ajpanel/new/emil-panel-lite.sh"},
        {"name": "Ciefp-Panel", "pic": "link.png", "url": "https://github.com/ciefp/CiefpsettingsPanel/raw/main/installer.sh"},
        {"name": "Ciefp-Panel mod Emil Nabil", "pic": "link.png", "url": "https://github.com/emilnabil/download-plugins/raw/refs/heads/main/Ciefp-Panel/Ciefp-Panel.sh"},
        {"name": "dreamosat-downloader", "pic": "link.png", "url": "https://dreambox4u.com/emilnabil237/plugins/dreamosat-downloader/installer.sh"},
        {"name": "EmilPanel", "pic": "link.png", "url": "https://github.com/emilnabil/download-plugins/raw/refs/heads/main/EmilPanel/emilpanel.sh"},
        {"name": "EmilPanelpro", "pic": "link.png", "url": "https://github.com/emilnabil/download-plugins/raw/refs/heads/main/EmilPanelPro/emilpanelpro.sh"},
        {"name": "EliesatPanel", "pic": "link.png", "url": "https://raw.githubusercontent.com/eliesat/eliesatpanel/main/installer.sh"},
        {"name": "Epanel", "pic": "link.png", "url": "https://dreambox4u.com/emilnabil237/plugins/epanel/installer.sh"},
        {"name": "linuxsat-panel", "pic": "link.png", "url": "https://raw.githubusercontent.com/Belfagor2005/LinuxsatPanel/main/installer.sh"},
        {"name": "levi45-AddonsManager", "pic": "link.png", "url": "https://dreambox4u.com/emilnabil237/plugins/levi45-addonsmanager/installer.sh"},
        {"name": "Levi45MulticamManager", "pic": "link.png", "url": "https://dreambox4u.com/emilnabil237/plugins/levi45multicammanager/installer.sh"},
        {"name": "MagicPanel-HAMDY_AHMED", "pic": "link.png", "url": "https://gitlab.com/h-ahmed/Panel/-/raw/main/MagicPanel_install.sh"},
        {"name": "SatVenusPanel", "pic": "link.png", "url": "https://dreambox4u.com/emilnabil237/plugins/satvenuspanel/installer.sh"},
        {"name": "Tspanel", "pic": "link.png", "url": "https://dreambox4u.com/emilnabil237/plugins/tspanel/installer.sh"},
        {"name": "SmartAddonspanel", "pic": "link.png", "url": "https://raw.githubusercontent.com/emilnabil/download-plugins/refs/heads/main/SmartAddonspanel/smart-Panel.sh"},
        {"name": "TvAddon-Panel", "pic": "link.png", "url": "https://dreambox4u.com/emilnabil237/plugins/tvaddon/installer.sh"}
    ],

    "Plugins": [
        {"name": "ArabicSavior", "pic": "link.png", "url": "http://dreambox4u.com/emilnabil237/plugins/ArabicSavior/installer.sh"},
        {"name": "Acherone", "pic": "link.png", "url": "https://raw.githubusercontent.com/emilnabil/download-plugins/refs/heads/main/acherone/installer.sh"},
        {"name": "Advanced-Screen-Shot", "pic": "link.png", "url": "https://raw.githubusercontent.com/Belfagor2005/AdvancedScreenshot/main/installer.sh"},
        {"name": "Alajre", "pic": "link.png", "url": "https://dreambox4u.com/emilnabil237/plugins/alajre/installer.sh"},
        {"name": "Ansite", "pic": "link.png", "url": "https://raw.githubusercontent.com/emil237/ansite/refs/heads/main/installer.sh"},
        {"name": "Apod", "pic": "link.png", "url": "https://raw.githubusercontent.com/emilnabil/download-plugins/refs/heads/main/apod/installer.sh"},
        {"name": "Astronomy", "pic": "link.png", "url": "https://raw.githubusercontent.com/emilnabil/download-plugins/refs/heads/main/astronomy/installer.sh"},
        {"name": "Athan Times", "pic": "link.png", "url": "https://dreambox4u.com/emilnabil237/plugins/athantimes/installer.sh"},
        {"name": "Atilehd", "pic": "link.png", "url": "https://dreambox4u.com/emilnabil237/plugins/atilehd/installer.sh"},
        {"name": "automatic-fullbackup", "pic": "link.png", "url": "https://dreambox4u.com/emilnabil237/plugins/automatic-fullbackup/installer.sh"},
        {"name": "Azkar Almuslim", "pic": "link.png", "url": "https://dreambox4u.com/emilnabil237/plugins/azkar-almuslim/installer.sh"},
        {"name": "Bitrate", "pic": "link.png", "url": "https://raw.githubusercontent.com/emilnabil/download-plugins/refs/heads/main/bitrate/bitrate.sh"},
        {"name": "Bitrate-mod-ariad", "pic": "link.png", "url": "https://raw.githubusercontent.com/emilnabil/download-plugins/refs/heads/main/bitrate/bitrate-mod-ariad.sh"},
        {"name": "Bundesliga-Permanent-Clock", "pic": "link.png", "url": "https://raw.githubusercontent.com/emilnabil/download-plugins/refs/heads/main/bundesliga-permanent-clock/bundesliga-permanent-clock.sh"},
        {"name": "CacheFlush", "pic": "link.png", "url": "https://raw.githubusercontent.com/emilnabil/download-plugins/refs/heads/main/cacheflush/cacheflush.sh"},
        {"name": "CCcaminfo-py2", "pic": "link.png", "url": "https://raw.githubusercontent.com/emilnabil/download-plugins/refs/heads/main/cccaminfo/cccaminfo_py2.sh"},
        {"name": "CCcaminfo-py3", "pic": "link.png", "url": "https://raw.githubusercontent.com/emilnabil/download-plugins/refs/heads/main/cccaminfo/cccaminfo_py3.sh"},
        {"name": "CrondManager", "pic": "link.png", "url": "https://raw.githubusercontent.com/emilnabil/download-plugins/refs/heads/main/crondmanager/installer.sh"},
        {"name": "CFG_ZOOM_FINAL", "pic": "link.png", "url": "https://dreambox4u.com/emilnabil237/plugins/cfg_Zoom_Final_FIX7x/installer.sh"},
        {"name": "CiefpBouquetUpdater", "pic": "link.png", "url": "https://raw.githubusercontent.com/ciefp/CiefpBouquetUpdater/main/installer.sh"},
        {"name": "CiefpIPTVBouquets", "pic": "link.png", "url": "https://raw.githubusercontent.com/ciefp/CiefpIPTVBouquets/main/installer.sh"},
        {"name": "CiefpSatelliteXmlEditor", "pic": "link.png", "url": "https://raw.githubusercontent.com/ciefp/CiefpSatelliteXmlEditor/main/installer.sh"},
        {"name": "CiefpSettingsDownloader", "pic": "link.png", "url": "https://raw.githubusercontent.com/ciefp/CiefpSettingsDownloader/main/installer.sh"},
        {"name": "CiefpsettingsMotor", "pic": "link.png", "url": "https://raw.githubusercontent.com/ciefp/CiefpsettingsMotor/main/installer.sh"},
        {"name": "CiefpSelectSatellite", "pic": "link.png", "url": "https://raw.githubusercontent.com/ciefp/CiefpSelectSatellite/main/installer.sh"},
        {"name": "CiefpE2Converter", "pic": "link.png", "url": "https://raw.githubusercontent.com/ciefp/CiefpE2Converter/main/installer.sh"},
        {"name": "Ciefp-Plugins", "pic": "link.png", "url": "https://raw.githubusercontent.com/ciefp/CiefpPlugins/main/installer.sh"},
        {"name": "CiefpWhitelistStreamrelay", "pic": "link.png", "url": "https://raw.githubusercontent.com/ciefp/CiefpWhitelistStreamrelay/main/installer.sh"},
        {"name": "CiefpSettingsStreamrela_PY3", "pic": "link.png", "url": "https://raw.githubusercontent.com/ciefp/CiefpSettingsStreamrelay/main/installer.sh"},
        {"name": "CiefpSettingsStreamrela_PY2", "pic": "link.png", "url": "https://raw.githubusercontent.com/ciefp/CiefpSettingsStreamrelayPY2/main/installer.sh"},
        {"name": "CiefpSettingsT2miAbertis", "pic": "link.png", "url": "https://raw.githubusercontent.com/ciefp/CiefpSettingsT2miAbertis/main/installer.sh"},
        {"name": "CiefpSettingsT2miAbertisOpenPLi", "pic": "link.png", "url": "https://raw.githubusercontent.com/ciefp/CiefpSettingsT2miAbertisOpenPLi/main/installer.sh"},
        {"name": "chocholousek-picons", "pic": "link.png", "url": "https://raw.githubusercontent.com/emilnabil/download-plugins/refs/heads/main/chocholousek-picons.sh"},
        {"name": "CHLogoChanger", "pic": "link.png", "url": "https://dreambox4u.com/emilnabil237/plugins/CHLogoChanger/ChLogoChanger.sh"},
        {"name": "CrashLogoViewer", "pic": "link.png", "url": "https://dreambox4u.com/emilnabil237/plugins/crashlogviewer/install-CrashLogViewer.sh"},
        {"name": "CrondManger", "pic": "link.png", "url": "https://github.com/emil237/download-plugins/raw/main/cronmanager.sh"},
        {"name": "Easy-Cccam", "pic": "link.png", "url": "https://gitlab.com/eliesat/extensions/-/raw/main/easy-cccam/easy-cccam.sh"},
        {"name": "enigma2readeradder", "pic": "link.png", "url": "https://raw.githubusercontent.com/emilnabil/download-plugins/refs/heads/main/enigma2readeradder.sh"},
        {"name": "Epg Grabber", "pic": "link.png", "url": "https://dreambox4u.com/emilnabil237/plugins/Epg-Grabber/installer.sh"},
        {"name": "EPGImport", "pic": "link.png", "url": "https://raw.githubusercontent.com/emilnabil/download-plugins/refs/heads/main/epgimport.sh"},
        {"name": "EPGImport-99", "pic": "link.png", "url": "https://raw.githubusercontent.com/Belfagor2005/EPGImport-99/main/installer.sh"},
        {"name": "EPGTranslator", "pic": "link.png", "url": "https://raw.githubusercontent.com/emilnabil/download-plugins/refs/heads/main/epgtranslator.sh"},
        {"name": "Filmxy", "pic": "link.png", "url": "https://raw.githubusercontent.com/emilnabil/download-plugins/refs/heads/main/filmxy/filmxy.sh"},
        {"name": "Footonsat", "pic": "link.png", "url": "https://dreambox4u.com/emilnabil237/plugins/FootOnsat/installer.sh"},
        {"name": "Freearhey", "pic": "link.png", "url": "https://raw.githubusercontent.com/emilnabil/download-plugins/refs/heads/main/freearhey/freearhey.sh"},
        {"name": "FreeCCcamServer", "pic": "link.png", "url": "https://ia803104.us.archive.org/0/items/freecccamserver/installer.sh"},
        {"name": "gioppygio", "pic": "link.png", "url": "https://raw.githubusercontent.com/emilnabil/download-plugins/refs/heads/main/gioppygio/gioppygio.sh"},
        {"name": "hardwareinfo", "pic": "link.png", "url": "https://dreambox4u.com/emilnabil237/plugins/hardwareinfo/installer.sh"},
        {"name": "HasBahCa", "pic": "link.png", "url": "https://dreambox4u.com/emilnabil237/plugins/HasBahCa/installer.sh"},
        {"name": "HistoryZapSelector", "pic": "link.png", "url": "https://dreambox4u.com/emilnabil237/plugins/historyzap/installer1.sh"},
        {"name": "horoscope", "pic": "link.png", "url": "https://raw.githubusercontent.com/emilnabil/horoscope/refs/heads/main/horoscope.sh"},
        {"name": "HolidayCountdown", "pic": "link.png", "url": "https://raw.githubusercontent.com/emilnabil/download-plugins/refs/heads/main/HolidayCountdown/installer.sh"},
        {"name": "Internet-Speedtest", "pic": "link.png", "url": "https://raw.githubusercontent.com/emilnabil/download-plugins/refs/heads/main/internet-speedtest.sh"},
        {"name": "Iptv-Org-Playlists", "pic": "link.png", "url": "https://raw.githubusercontent.com/emilnabil/download-plugins/refs/heads/main/iptv-org-playlists/iptv-org-playlists.sh"},
        {"name": "iptvdream", "pic": "link.png", "url": "https://raw.githubusercontent.com/emilnabil/download-plugins/main/iptvdream/iptvdream.sh"},
        {"name": "levi45-settings", "pic": "link.png", "url": "https://dreambox4u.com/emilnabil237/plugins/levi45-settings/levi45-settings.sh"},
        {"name": "M3uConverter", "pic": "link.png", "url": "https://raw.githubusercontent.com/Belfagor2005/Archimede-M3UConverter/main/installer.sh"},
        {"name": "MoviesManager", "pic": "link.png", "url": "http://dreambox4u.com/emilnabil237/plugins/Transmission/MoviesManager.sh"},
        {"name": "MyCam-Plugin", "pic": "link.png", "url": "https://dreambox4u.com/emilnabil237/plugins/mycam/installer.sh"},
        {"name": "MultiCamAdder", "pic": "link.png", "url": "https://raw.githubusercontent.com/emilnabil/download-plugins/refs/heads/main/MultiCamAdder/installer.sh"},
        {"name": "Multi-Iptv-Adder", "pic": "link.png", "url": "https://raw.githubusercontent.com/emilnabil/download-plugins/refs/heads/main/MultiIptvAdder/installer.sh"},
        {"name": "NewVirtualkeyBoard", "pic": "link.png", "url": "https://dreambox4u.com/emilnabil237/plugins/NewVirtualKeyBoard/installer.sh"},
        {"name": "ONEupdater", "pic": "link.png", "url": "https://raw.githubusercontent.com/Sat-Club/ONEupdaterE2/main/installer.sh"},
        {"name": "Ozeta-Skins-Setup", "pic": "link.png", "url": "https://raw.githubusercontent.com/emil237/skins-enigma2/main/PLUGIN_Skin-ozeta.sh"},
        {"name": "Plutotv", "pic": "link.png", "url": "https://raw.githubusercontent.com/emilnabil/download-plugins/main/plutotv/plutotv.sh"},
        {"name": "Quran-karem", "pic": "link.png", "url": "https://dreambox4u.com/emilnabil237/plugins/quran/installer.sh"},
        {"name": "Quran-karem_v2.2", "pic": "link.png", "url": "https://raw.githubusercontent.com/emil237/quran/main/installer.sh"},
        {"name": "Radio-80-s", "pic": "link.png", "url": "https://raw.githubusercontent.com/Belfagor2005/Radio-80-s/main/installer.sh"},
        {"name": "RadioGit", "pic": "link.png", "url": "https://dreambox4u.com/emilnabil237/plugins/radiogit/radiogit.sh"},
        {"name": "Radiom", "pic": "link.png", "url": "https://raw.githubusercontent.com/emilnabil/download-plugins/main/radiom/radiom.sh"},
        {"name": "Rakutentv", "pic": "link.png", "url": "https://raw.githubusercontent.com/emilnabil/download-plugins/main/rakutentv/rakutentv.sh"},
        {"name": "RaedQuickSignal", "pic": "link.png", "url": "https://dreambox4u.com/emilnabil237/plugins/RaedQuickSignal/installer.sh"},
        {"name": "pluginmover", "pic": "link.png", "url": "http://dreambox4u.com/emilnabil237/plugins/pluginmover/installer.sh"},
        {"name": "pluginskinmover", "pic": "link.png", "url": "http://dreambox4u.com/emilnabil237/plugins/pluginskinmover/installer.sh"},
        {"name": "ScreenNames", "pic": "link.png", "url": "https://raw.githubusercontent.com/emilnabil/download-plugins/refs/heads/main/screennames/screennames.sh"},
        {"name": "Screen-Recorder", "pic": "link.png", "url": "https://raw.githubusercontent.com/emilnabil/download-plugins/refs/heads/main/screenrecorder/installer.sh"},
        {"name": "SetPicon", "pic": "link.png", "url": "https://raw.githubusercontent.com/emilnabil/download-plugins/refs/heads/main/setpicon/installer.sh"},
        {"name": "scriptexecuter", "pic": "link.png", "url": "http://dreambox4u.com/emilnabil237/plugins/scriptexecuter/installer.sh"},
        {"name": "Sherlockmod", "pic": "link.png", "url": "https://raw.githubusercontent.com/emil237/sherlockmod/main/installer.sh"},
        {"name": "Simple-Zoom-Panel", "pic": "link.png", "url": "https://dreambox4u.com/emilnabil237/plugins/simple-zoom-panel/installer.sh"},
        {"name": "SubsSupport_1.5.8-r9", "pic": "link.png", "url": "https://dreambox4u.com/emilnabil237/plugins/SubsSupport/installer1.sh"},
        {"name": "SubsSupport_by-m.nasr", "pic": "link.png", "url": "https://github.com/popking159/ssupport/raw/main/subssupport-install.sh"},
        {"name": "SubsSupport_2.1", "pic": "link.png", "url": "https://dreambox4u.com/emilnabil237/plugins/SubsSupport/subssupport_2.1.sh"},
        {"name": "uninstaller-Plugins", "pic": "link.png", "url": "http://dreambox4u.com/emilnabil237/plugins/unstaller-plugins/installer.sh"},
        {"name": "vavoo_1.15", "pic": "link.png", "url": "https://dreambox4u.com/emilnabil237/plugins/vavoo/installer.sh"},
        {"name": "xtraevent_3.3", "pic": "link.png", "url": "https://raw.githubusercontent.com/emil237/download-plugins/main/xtraevent_3.3.sh"},
        {"name": "xtraevent_4.2", "pic": "link.png", "url": "https://raw.githubusercontent.com/emil237/download-plugins/main/xtraEvent_4.2.sh"},
        {"name": "xtraevent_4.5", "pic": "link.png", "url": "https://raw.githubusercontent.com/emil237/download-plugins/main/xtraEvent_4.5.sh"},
        {"name": "Xtraevent_4.6", "pic": "link.png", "url": "https://github.com/emil237/download-plugins/raw/main/Xtraevent-v4.6.sh"},
        {"name": "xtraevent_6.798", "pic": "link.png", "url": "https://dreambox4u.com/emilnabil237/plugins/xtraevent/xtraevent_6.798.sh"},
        {"name": "xtraevent_6.805", "pic": "link.png", "url": "https://dreambox4u.com/emilnabil237/plugins/xtraevent/xtraevent-6.805.sh"},
        {"name": "xtraevent_6.820_All-Python", "pic": "link.png", "url": "https://dreambox4u.com/emilnabil237/plugins/xtraevent/xtraevent-6.820.sh"},
        {"name": "WorldCam", "pic": "link.png", "url": "https://raw.githubusercontent.com/Belfagor2005/WorldCam/main/installer.sh"},
        {"name": "Zip2Pkg-Converter", "pic": "link.png", "url": "https://raw.githubusercontent.com/emilnabil/download-plugins/refs/heads/main/Zip2Pkg/installer.sh"},
        {"name": "Zoom_1.1.2-Py3", "pic": "link.png", "url": "https://dreambox4u.com/emilnabil237/plugins/zoom/installer.sh"}
    ],

    "BackupSettings": [
        {"name": "Backup-my-shannels", "pic": "link.png", "url": "http://dreambox4u.com/emilnabil237/script/Create-My-backup-shannels.sh"},
        {"name": "Backup-hotkey", "pic": "link.png", "url": "http://dreambox4u.com/emilnabil237/script/backup-hotkey.sh"},
        {"name": "Backup-network", "pic": "link.png", "url": "http://dreambox4u.com/emilnabil237/script/backup-network.sh"},
        {"name": "Backup-softcams", "pic": "link.png", "url": "http://dreambox4u.com/emilnabil237/script/backup-softcams.sh"},
        {"name": "Backup-tuner", "pic": "link.png", "url": "http://dreambox4u.com/emilnabil237/script/backup-tuner.sh"},
        {"name": "Backup-my-bouquetmakerxtream", "pic": "link.png", "url": "http://dreambox4u.com/emilnabil237/script/backup-my-bouquetmakerxtream.sh"},
        {"name": "Backup-my-ip2sat-server", "pic": "link.png", "url": "http://dreambox4u.com/emilnabil237/script/backup-my-ip2sat-server.sh"},
        {"name": "Backup-my-ipaudio-server", "pic": "link.png", "url": "http://dreambox4u.com/emilnabil237/script/backup-my-ipaudio-server.sh"},
        {"name": "Backup-my-ipaudiopro-server", "pic": "link.png", "url": "http://dreambox4u.com/emilnabil237/script/backup-my-ipaudiopro-server.sh"},
        {"name": "Backup-my-jediplaylists", "pic": "link.png", "url": "http://dreambox4u.com/emilnabil237/script/backup-my-jediplaylists.sh"},
        {"name": "Backup-my-multistalkerpro", "pic": "link.png", "url": "http://dreambox4u.com/emilnabil237/script/backup-my-multistalkerpro.sh"},
        {"name": "Backup-my-Subtitle-Setting", "pic": "link.png", "url": "http://dreambox4u.com/emilnabil237/script/backup_my-subtitle-setting.sh"},
        {"name": "Backup-my-xstreamity-servers", "pic": "link.png", "url": "http://dreambox4u.com/emilnabil237/script/backup-my-xstreamity-servers.sh"},
        {"name": "Backup-sittings-xtraevent", "pic": "link.png", "url": "http://dreambox4u.com/emilnabil237/script/backup-sittings-xtraevent.sh"}
    ],

    "RestoreSettings": [
        {"name": "Restore-my-shannels", "pic": "link.png", "url": "http://dreambox4u.com/emilnabil237/script/Restore-My-backup-shannels.sh"},
        {"name": "Restore-hotkey", "pic": "link.png", "url": "http://dreambox4u.com/emilnabil237/script/resore-hotkey.sh"},
        {"name": "Restore-network", "pic": "link.png", "url": "http://dreambox4u.com/emilnabil237/script/restore-network.sh"},
        {"name": "Restore-softcams", "pic": "link.png", "url": "http://dreambox4u.com/emilnabil237/script/restore-softcams.sh"},
        {"name": "Restore-tuner", "pic": "link.png", "url": "http://dreambox4u.com/emilnabil237/script/restore-tuner.sh"},
        {"name": "Restore-my-bouquetmakerxtream", "pic": "link.png", "url": "http://dreambox4u.com/emilnabil237/script/restore-my-bouquetmakerxtream.sh"},
        {"name": "Restore-my-ip2sat-server", "pic": "link.png", "url": "http://dreambox4u.com/emilnabil237/script/restore-my-ip2sat-server.sh"},
        {"name": "Restore-my-ipaudio-server", "pic": "link.png", "url": "http://dreambox4u.com/emilnabil237/script/restore-my-ipaudio-server.sh"},
        {"name": "Restore-my-ipaudiopro-server", "pic": "link.png", "url": "http://dreambox4u.com/emilnabil237/script/restore-my-ipaudiopro-server.sh"},
        {"name": "Restore-my-jediplaylists", "pic": "link.png", "url": "http://dreambox4u.com/emilnabil237/script/restore-my-jediplaylists.sh"},
        {"name": "Restore-my-multistalkerpro", "pic": "link.png", "url": "http://dreambox4u.com/emilnabil237/script/restore-my-multistalkerpro.sh"},
        {"name": "Restore-My-Subtitle-Setting", "pic": "link.png", "url": "http://dreambox4u.com/emilnabil237/script/Restore_my-subtitle-setting.sh"},
        {"name": "Restore-my-xstreamity-servers", "pic": "link.png", "url": "http://dreambox4u.com/emilnabil237/script/restore-my-xstreamity-servers.sh"},
        {"name": "Restore-sittings-xtraevent", "pic": "link.png", "url": "http://dreambox4u.com/emilnabil237/script/restore-sittings-xtraevent.sh"}
    ],

    "Images": [
        {"name": "BlackHole-3.1.0", "pic": "link.png", "url": "https://dreambox4u.com/emilnabil237/images/BlackHole-3.1.0.sh"},
        {"name": "Egami-10.4", "pic": "link.png", "url": "https://dreambox4u.com/emilnabil237/images/egami-10.4.sh"},
        {"name": "Openatv-6.4", "pic": "link.png", "url": "https://dreambox4u.com/emilnabil237/images/openatv-6.4.sh"},
        {"name": "Openatv-7.0", "pic": "link.png", "url": "https://dreambox4u.com/emilnabil237/images/openatv-7.0.sh"},
        {"name": "Openatv-7.1", "pic": "link.png", "url": "https://dreambox4u.com/emilnabil237/images/openatv-7.1.sh"},
        {"name": "Openatv-7.2", "pic": "link.png", "url": "https://dreambox4u.com/emilnabil237/images/openatv-7.2.sh"},
        {"name": "Openatv-7.3", "pic": "link.png", "url": "https://dreambox4u.com/emilnabil237/images/openatv-7.3.sh"},
        {"name": "Openatv-7.4", "pic": "link.png", "url": "https://dreambox4u.com/emilnabil237/images/openatv-7.4.sh"},
        {"name": "Openatv-7.5", "pic": "link.png", "url": "https://dreambox4u.com/emilnabil237/images/openatv-7.5.sh"},
        {"name": "Openatv-7.5.1", "pic": "link.png", "url": "https://dreambox4u.com/emilnabil237/images/openatv-7.5.1.sh"},
        {"name": "Openatv-7.6", "pic": "link.png", "url": "https://dreambox4u.com/emilnabil237/images/openatv-7.6.sh"},
        {"name": "OpenBlackHole-4.4", "pic": "link.png", "url": "https://dreambox4u.com/emilnabil237/images/openblackhole-4.4-for-vuplus-only.sh"},
        {"name": "OpenBlackHole-5.0", "pic": "link.png", "url": "https://dreambox4u.com/emilnabil237/images/openblackhole-5.0.sh"},
        {"name": "OpenBlackHole-5.1", "pic": "link.png", "url": "https://dreambox4u.com/emilnabil237/images/openblackhole-5.1.sh"},
        {"name": "OpenBlackHole-5.2", "pic": "link.png", "url": "https://dreambox4u.com/emilnabil237/images/openblackhole-5.2.sh"},
        {"name": "OpenBlackHole-5.3", "pic": "link.png", "url": "https://dreambox4u.com/emilnabil237/images/openblackhole-5.3.sh"},
        {"name": "OpenBlackHole-5.4", "pic": "link.png", "url": "https://dreambox4u.com/emilnabil237/images/openblackhole-5.4.sh"},
        {"name": "OpenBlackHole-5.5.1", "pic": "link.png", "url": "https://dreambox4u.com/emilnabil237/images/openblackhole-5.5.1.sh"},
        {"name": "OpenDroid-7.1", "pic": "link.png", "url": "https://dreambox4u.com/emilnabil237/images/opendroid-7.1.sh"},
        {"name": "Openpli-7.3", "pic": "link.png", "url": "https://dreambox4u.com/emilnabil237/images/openpli-7.3.sh"},
        {"name": "OpenPli-8.3", "pic": "link.png", "url": "https://dreambox4u.com/emilnabil237/images/openpli-8.3.sh"},
        {"name": "OpenPli-8.3-Time-Shift", "pic": "link.png", "url": "https://dreambox4u.com/emilnabil237/images/openpli-8.3-py2-TimeShift.sh"},
        {"name": "OpenPli-9.0-Time-Shift", "pic": "link.png", "url": "https://dreambox4u.com/emilnabil237/images/openpli-9.0-py3-TimeShift.sh"},
        {"name": "OpenPli-9.0", "pic": "link.png", "url": "https://dreambox4u.com/emilnabil237/images/openpli-9.0.sh"},
        {"name": "OpenPli-9.1", "pic": "link.png", "url": "https://dreambox4u.com/emilnabil237/images/openpli-9.1.sh"},
        {"name": "OpenPli-develop", "pic": "link.png", "url": "https://dreambox4u.com/emilnabil237/images/openpli-develop.sh"},
        {"name": "openspa-7.5.xxx", "pic": "link.png", "url": "https://dreambox4u.com/emilnabil237/images/openspa-7.5.xxx.sh"},
        {"name": "openspa-8.0.xxx", "pic": "link.png", "url": "https://dreambox4u.com/emilnabil237/images/openspa-8.0.xxx.sh"},
        {"name": "openspa-8.1.xxx", "pic": "link.png", "url": "https://dreambox4u.com/emilnabil237/images/openspa-8.1.xxx.sh"},
        {"name": "openspa-8.3.xxx", "pic": "link.png", "url": "https://dreambox4u.com/emilnabil237/images/openspa-8.3.xxx.sh"},
        {"name": "openspa-8.4.xxx", "pic": "link.png", "url": "https://dreambox4u.com/emilnabil237/images/openspa-8.4.xxx.sh"},
        {"name": "Openvix-6.6.004", "pic": "link.png", "url": "https://dreambox4u.com/emilnabil237/images/openvix-6.6.004.sh"},
        {"name": "openvix_latest-version", "pic": "link.png", "url": "https://dreambox4u.com/emilnabil237/images/openvix_latest-version.sh"},
        {"name": "OpenVision-py2-10.3-r395", "pic": "link.png", "url": "https://dreambox4u.com/emilnabil237/images/openvision/OpenVision-py2-10.3-r395.sh"},
        {"name": "pure2-6.5", "pic": "link.png", "url": "https://dreambox4u.com/emilnabil237/images/pure2-6.5.sh"},
        {"name": "pure2-7.3", "pic": "link.png", "url": "https://dreambox4u.com/emilnabil237/images/pure2-7.3.sh"},
        {"name": "pure2-7.4", "pic": "link.png", "url": "https://dreambox4u.com/emilnabil237/images/pure2-7.4.sh"},
        {"name": "VTI-15.0.02", "pic": "link.png", "url": "https://dreambox4u.com/emilnabil237/images/vti-15.0.02.sh"}
    ]
}
